<?php

function geraProtocolo($processoNumero, $processoAno){

//protocolo e ano
$protocoloNum = $processoNumero;
$protocoloAno = $processoAno;

////////////////// PROCURA E CRIA AS VARIÁVEIS GERADAS PELO SERVIDOR /////////////////////

$ch = curl_init('https://vinhedogpm.presconinformatica.com.br/ords/gpmodvnh/f?p=207:1::::::');
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// get headers too with this line
curl_setopt($ch, CURLOPT_HEADER, 1);
$result = curl_exec($ch);


$PO_USUARIO_LOGADO = explode('data-for="P0_USUARIO_LOGADO" value="', $result);
$PO_USUARIO_LOGADO = explode('">', $PO_USUARIO_LOGADO[1]);
$PO_USUARIO_LOGADO = $PO_USUARIO_LOGADO[0];
//echo $PO_USUARIO_LOGADO . "<br>";

$DATASOURCE_REPORTS = explode('data-for="DATASOURCE_REPORTS" value="', $result);
$DATASOURCE_REPORTS = explode('">', $DATASOURCE_REPORTS[1]);
$DATASOURCE_REPORTS = $DATASOURCE_REPORTS[0];
//echo $DATASOURCE_REPORTS . "<br>";

$URL_REPORTS = explode('data-for="URL_REPORTS" value="', $result);
$URL_REPORTS = explode('">', $URL_REPORTS[1]);
$URL_REPORTS = $URL_REPORTS[0];
//echo $URL_REPORTS . "<br>";

$P0_ID_PESSOA = explode('data-for="P0_ID_PESSOA" value="', $result);
$P0_ID_PESSOA = explode('">', $P0_ID_PESSOA[1]);
$P0_ID_PESSOA = $P0_ID_PESSOA[0];
//echo $P0_ID_PESSOA . "<br>";

$P0_NOME_PESSOA = explode('data-for="P0_NOME_PESSOA" value="', $result);
$P0_NOME_PESSOA = explode('">', $P0_NOME_PESSOA[1]);
$P0_NOME_PESSOA = $P0_NOME_PESSOA[0];
//echo $P0_NOME_PESSOA . "<br>";

$P0_ENTIDADE = explode('data-for="P0_ENTIDADE" value="', $result);
$P0_ENTIDADE = explode('">', $P0_ENTIDADE[1]);
$P0_ENTIDADE = $P0_ENTIDADE[0];
//echo $P0_ENTIDADE . "<br>";

$REPNAME_REPORTS = explode('data-for="REPNAME_REPORTS" value="', $result);
$REPNAME_REPORTS = explode('">', $REPNAME_REPORTS[1]);
$REPNAME_REPORTS = $REPNAME_REPORTS[0];
//echo $REPNAME_REPORTS . "<br>";

$protected = explode('id="pPageItemsProtected" value="', $result);
$protected = explode('" />', $protected[1]);
$protected = $protected[0];
//echo $protected . "<br>";

$salt = explode('id="pReloadOnSubmit" /><input type="hidden" value="', $result);
$salt = explode('" id="pSalt" />', $salt[1]);
$salt = $salt[0];
//echo $salt . "<br>";

$pinstance = explode('name="p_instance" value="', $result);
$pinstance = explode('" id="pInstance"', $pinstance[1]);
$pinstance = $pinstance[0];

//echo $pinstance . "<br>";

$p_request = explode('src="wwv_flow.show?p_request=NATIVE%', $result);
$p_request = explode('&', $p_request[1]);
$p_request = $p_request[0];
//echo $p_request ."<br>";

///// pega os cookies gerados e seta a variável do cookie
// multi-cookie variant contributed by @Combuster in comments
preg_match_all('/^Set-Cookie:\s*([^;]*)/mi', $result, $matches);
$cookies = array();
foreach($matches[1] as $item) {
    parse_str($item, $cookie);
    $cookies = array_merge($cookies, $cookie);
}

$cookieLogin = $cookies['LOGIN_COOKIE'];
//echo $cookieLogin;
//var_dump($cookies);

////////////// ENVIA AS VARIÁVEIS AO SERVIDOR DO WEBSITE /////////////////////

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://vinhedogpm.presconinformatica.com.br/ords/gpmodvnh/wwv_flow.accept');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "p_flow_id=207&p_flow_step_id=1&p_instance=$pinstance&p_debug=&p_request=PESQUISAR&p_reload_on_submit=S&p_page_submission_id=$salt&p_json=%7B%22pageItems%22%3A%7B%22itemsToSubmit%22%3A%5B%7B%22n%22%3A%22P0_USUARIO_LOGADO%22%2C%22v%22%3A%22%22%2C%22ck%22%3A%22$PO_USUARIO_LOGADO%22%7D%2C%7B%22n%22%3A%22DATASOURCE_REPORTS%22%2C%22v%22%3A%22GPMOD_VNH%22%2C%22ck%22%3A%22$DATASOURCE_REPORTS%22%7D%2C%7B%22n%22%3A%22URL_REPORTS%22%2C%22v%22%3A%22http%3A%2F%2F144.22.105.63%3A8080%2FJasperReportsIntegration%2Freport%22%2C%22ck%22%3A%22$URL_REPORTS%22%7D%2C%7B%22n%22%3A%22P0_ID_PESSOA%22%2C%22v%22%3A%22%22%2C%22ck%22%3A%22$P0_ID_PESSOA%22%7D%2C%7B%22n%22%3A%22P0_NOME_PESSOA%22%2C%22v%22%3A%22%22%2C%22ck%22%3A%22$P0_NOME_PESSOA%22%7D%2C%7B%22n%22%3A%22P0_ENTIDADE%22%2C%22v%22%3A%223%22%2C%22ck%22%3A%22$P0_ENTIDADE%22%7D%2C%7B%22n%22%3A%22REPNAME_REPORTS%22%2C%22v%22%3A%22GPMod%2FVinhedo%2FProtocolo%2F%22%2C%22ck%22%3A%22$REPNAME_REPORTS%22%7D%2C%7B%22n%22%3A%22P1_OPCAO%22%2C%22v%22%3A%221%22%7D%2C%7B%22n%22%3A%22P1_SHOW%22%2C%22v%22%3A%220%22%7D%2C%7B%22n%22%3A%22P1_TIPOPESQUISA%22%2C%22v%22%3A%221%22%7D%2C%7B%22n%22%3A%22P1_PROCESSO%22%2C%22v%22%3A%22$protocoloNum%22%7D%2C%7B%22n%22%3A%22P1_ANO%22%2C%22v%22%3A%22$protocoloAno%22%7D%2C%7B%22n%22%3A%22P1_AUTENTICACAO%22%2C%22v%22%3A%22%22%7D%2C%7B%22n%22%3A%22P1_PESQUISADESCRICAO%22%2C%22v%22%3A%22%22%7D%2C%7B%22n%22%3A%22ID_RELATORIO%22%2C%22v%22%3A%22%22%7D%5D%2C%22protected%22%3A%22$protected%22%2C%22rowVersion%22%3A%22%22%7D%2C%22salt%22%3A%22$salt%22%7D");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Host: vinhedogpm.presconinformatica.com.br';
$headers[] = 'Accept: application/json, text/javascript, */*; q=0.01';
$headers[] = 'Origin: https://vinhedogpm.presconinformatica.com.br';
$headers[] = 'X-Requested-With: XMLHttpRequest';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36';
$headers[] = 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8';
$headers[] = 'Referer: https://vinhedogpm.presconinformatica.com.br/ords/gpmodvnh/f?p=207:1::::::';
$headers[] = 'Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6';
$headers[] = 'Cookie: LOGIN_COOKIE='.$cookieLogin;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    return 'Error:' . curl_error($ch);
}
curl_close($ch);


////////////////////////////// ÚLTIMO REQUEST PARA RETORNAR A PÁGINA COM A RESPOSTA DO SERVIDOR EM HTML ///////////////////////////////

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://vinhedogpm.presconinformatica.com.br/ords/gpmodvnh/f?p=207:1:'.$pinstance.'::NO:::');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Host: vinhedogpm.presconinformatica.com.br';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3';
$headers[] = 'Referer: https://vinhedogpm.presconinformatica.com.br/ords/gpmodvnh/f?p=207:1::::::';
$headers[] = 'Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6';
$headers[] = 'Cookie: LOGIN_COOKIE='.$cookieLogin;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    return 'Error:' . curl_error($ch);
}
curl_close($ch);

/////////////////// DEFININDO VARIÁVEIS ANTES DE GERAR A TABELA * será usado explode mesmo tendo mais que 1 tipo de retorno por que interessa apenas o de cima

$requerente = explode('<span id="P1_REQUERENTE_error_placeholder" class="a-Form-error" data-template-id="9685340192569599122_ET"></span>
<span id="P1_REQUERENTE"  class="display_only&#x20;apex-item-display-only" >', $result);
$requerente = explode('</span></div>', $requerente[1]);
$requerente = $requerente[0];
//echo $requerente . "<br>";

$assunto = explode('<span id="P1_ASSUNTO_error_placeholder" class="a-Form-error" data-template-id="9685340192569599122_ET"></span>
<span id="P1_ASSUNTO"  class="display_only&#x20;apex-item-display-only" >', $result);
$assunto = explode('</span></div>', $assunto[1]);
$assunto = $assunto[0];
//echo $assunto . "<br>";

$processo = $protocoloNum;
$ano = $protocoloAno;

$tipoMovimento = explode('<td headers="Tipo Movimento" data-label="Tipo movimento" >', $result);
$tipoMovimento = explode('</td>', $tipoMovimento[1]);
$tipoMovimento = $tipoMovimento[0];

////DATA
$dataMoivemtacao = explode('<td headers="Data" data-label="Data" >', $result);
$dataMoivemtacao = explode('</td>', $dataMoivemtacao[1]);
$dataMoivemtacao = explode(' ', $dataMoivemtacao[0]);
$horarios = $dataMoivemtacao[1];
$dataMoivemtacao = explode('-', $dataMoivemtacao[0]);
$horarios = explode(':', $horarios);

// altera o nome dos meses para números e facilitar a alocação no array
switch ($dataMoivemtacao[1]) {
    case "JAN":
        $dataMoivemtacao[1] = "01";
        break;
    case "FEV":
        $dataMoivemtacao[1] = "02";
        break;
    case "MAR":
        $dataMoivemtacao[1] = "03";
        break;
	case "ABR":
        $dataMoivemtacao[1] = "04";
        break;
	case "MAI":
        $dataMoivemtacao[1] = "05";
        break;
	case "JUN":
        $dataMoivemtacao[1] = "06";
        break;
    case "JUL":
        $dataMoivemtacao[1] = "07";
        break;
    case "AGO":
        $dataMoivemtacao[1] = "08";
        break;
	case "SET":
        $dataMoivemtacao[1] = "09";
        break;
	case "OUT":
        $dataMoivemtacao[1] = "10";
        break;
	case "NOV":
        $dataMoivemtacao[1] = "11";
        break;
	case "DEZ":
        $dataMoivemtacao[1] = "12";
        break;
}

$despacho = explode('<td headers="Despacho" data-label="Despacho" >', $result);
$despacho = explode('</td>', $despacho[1]);
$despacho = $despacho[0];

$destino = explode('<td headers="Destino" data-label="Destino" >', $result);
$destino = explode('</td>', $destino[1]);
$destino = $destino[0];

$observacao = explode('<td headers="Observações" data-label="Observações" >', $result);
$observacao = explode('</td>', $observacao[1]);
$observacao = $observacao[0];

$out['ordem'] = $dataMoivemtacao[2] . $dataMoivemtacao[1] . $dataMoivemtacao[0] . "<br>" . $horarios[0] . $horarios[1];
$out['processo'] = $processo;
$out['ano'] = $ano;
$out['requerente'] = $requerente;
$out['assunto'] = $assunto;
$out['tipo'] = $tipoMovimento;
$out['data'] = $dataMoivemtacao[0] . "/" . $dataMoivemtacao[1] . "/" . $dataMoivemtacao[2];
$out['despacho'] = $despacho;
$out['destino'] = $destino;
$out['observacao'] = $observacao;

/// usa tag <divide> para dividir na saída

return $out;


}

/* CHAMANDO A FUNÇÃO
$prefProtocolo = geraProtocolo(5514,2018);
echo $prefProtocolo['requerente'] . "<br>";
echo $prefProtocolo['ordem'];
*/



?>

<?php
function timePHPProcess($start = null) {
$mTime = microtime(); // Pega o microtime
$mTime = explode(' ',$mTime); // Quebra o microtime
$mTime = $mTime[1] + $mTime[0]; // Soma as partes montando um valor inteiro
 
if ($start == null){
return $mTime;
}else{
return round($mTime - $start, 2);
}
}
?>